# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'AutoTest script Check'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: 'SimpleAPI-dotnet build $(buildConfiguration)'
  inputs:
    command: build
    publishWebProjects: false
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'SimpleAPI-dotnet publish $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'SimpleAPI 2 -dotnet build $(buildConfiguration)'
  inputs:
    command: build
    publishWebProjects: false
    projects: 'src/SimpleAPI2/SimpleAPI2.csproj'
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'SimpleAPI 2 -dotnet publish $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SimpleAPI2/SimpleAPI2.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true


- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'